### ISSUE TITLE
Failed to load preset 'S3_StutterBedont'

### ISSUE THREAD

**Issue by 130N1D** [sims3fiend/Sims3SettingsSetter#2]
![Screenshot_1](https://github.com/user-attachments/assets/05a36c1a-b005-45ad-835b-20c094ca8aee)

**Comment by sims3fiend** [comment]
Should be fixed via 06588d8d2e39b22069e907b036047e4bf7ed0ffc
Have uploaded to Sims File Share if you're using that also.
